# Ignore STARPU_TESTING-only blocks in SonarQube issues.
sonar.issue.ignore.block=starpu_testing
sonar.issue.ignore.block.starpu_testing.beginBlockRegexp=//\\s*SONAR_IGNORE_START
sonar.issue.ignore.block.starpu_testing.endBlockRegexp=//\\s*SONAR_IGNORE_END
